####################################################################################################
# Pipelex Model Deck - Base Configuration
####################################################################################################
#
# This file defines model aliases and presets for Document extraction models, including
# extraction of text and images from documents and OCR and text extraction from images.
#
# Model Reference Syntax:
# - Preset:    $preset_name or preset:preset_name
# - Alias:     @alias_name or alias:alias_name
#
# Documentation: https://docs.pipelex.com
# Support: https://go.pipelex.com/discord
#
####################################################################################################

####################################################################################################
# Document Extraction Default Choices
####################################################################################################

[extract]
choice_default = "$extract-all-from-document"

####################################################################################################
# Aliases
####################################################################################################

[extract.aliases]
default-extract-document = "azure-document-intelligence"
default-extract-text-from-pdf = "pypdfium2-extract-pdf"
default-software-extract-no-inference = "pypdfium2-extract-pdf"

####################################################################################################
# Extract Presets
####################################################################################################

[extract.presets]
extract-all-from-document = { model = "@default-extract-document", max_nb_images = 100, image_min_size = 50 }
extract-text-from-pdf = { model = "@default-extract-text-from-pdf", max_nb_images = 100, image_min_size = 50 }

# Testing
extract-testing = { model = "@default-software-extract-no-inference", max_nb_images = 100, image_min_size = 50 }
