
####################################################################################################
# Pipelex config
####################################################################################################

# [pipelex.pipeline_execution_config.graph_config.graphs_inclusion]
# Uncomment to customize which graph outputs are generated (all enabled by default):
# graphspec_json = false
# orchestration_mmd = false
# orchestration_html = false
# dataflow_mmd = false
# dataflow_html = false
# combo_mmd = false
# combo_html = false
# reactflow_viewspec = false
# reactflow_html = true


[pipelex.storage_config]
# Uncomment to change the storage method: "local" (default) or "in_memory"
method = "s3"
# Whether to fetch remote HTTP URLs and store them locally
# is_fetch_remote_content_enabled = true

# --- Local Storage Configuration ---
# Uncomment to customize local storage settings:
# [pipelex.storage_config.local]
# uri_format = "{primary_id}/{secondary_id}/{hash}.{extension}"
# local_storage_path = ".pipelex/storage"

# --- In-Memory Storage Configuration ---
# Uncomment to use in-memory storage (data is lost when process ends):
# [pipelex.storage_config.in_memory]
# uri_format = "{primary_id}/{secondary_id}/{hash}.{extension}"

# --- AWS S3 Storage Configuration ---
# Uncomment to use S3 storage (requires boto3: `pip install pipelex[s3]`):
[pipelex.storage_config.s3]
uri_format = "{primary_id}/{secondary_id}/{hash}.{extension}"
bucket_name = "pipelex-storage-test"
region = "eu-west-3"
signed_urls_lifespan_seconds = 3600                           # Set to "disabled" for public URLs

# --- Google Cloud Storage Configuration ---
# Uncomment to use GCP storage (requires google-cloud-storage: `pip install pipelex[gcp-storage]`):
# [pipelex.storage_config.gcp]
# uri_format = "{primary_id}/{secondary_id}/{hash}.{extension}"
# bucket_name = "your-bucket-name"
# project_id = "your-project-id"
# signed_urls_lifespan_seconds = 3600  # Set to "disabled" for public URLs

[pipelex.builder_config]
fix_loop_max_attempts = 10
# Uncomment to change where the generated pipelines are saved
default_output_dir = "./pipelines"
# default_bundle_file_name = "bundle"
# default_directory_base_name = "pipeline"

[pipelex.log_config]
default_log_level = "INFO"

[pipelex.log_config.package_log_levels]
pipelex = "DEBUG"

[cogt.model_deck_config]
is_model_fallback_enabled = true
# missing_presets_reaction = "raise"

[cogt.llm_config]
# is_dump_text_prompts_enabled = true
# is_dump_response_text_enabled = true

[cogt.llm_config.instructor_config]
# is_dump_kwargs_enabled = true
# is_dump_response_enabled = true
# is_dump_error_enabled = true

[cogt.llm_config.llm_job_config]
max_retries = 3
